development:
  address: "smtp.gmail.com"
  port: 587
  domain: "gmail.com"
  authentication: "plain"
  user_name: <%= ENV["action_mailer_user_name"] %>
  password: <%= ENV["action_mailer_password"] %>
  enable_starttls_auto: true

production:
  address: "smtp.sendgrid.net"
  port: 587
  domain: "heroku.com"
  authentication: "plain"
  user_name: <%= ENV["action_mailer_user_name"] %>
  password: <%= ENV["action_mailer_password"] %>
  enable_starttls_auto: true